#### REQUIRED ####
bam: "/mnt/mnt_data/dzj_dirs/mnt/mnt_data/dzj_dirs/css20x/Chr6D/output_prefix.sorted.bam"  # path to the alignments file (BAM/CRAM format)
fai: "/mnt/mnt_data/dzj_dirs/mnt/mnt_data/dzj_dirs/css20x/Chr6D/ref_wheat.fa.fai"  # path to the reference FASTA FAI file
#### OPTIONAL ####
n_cpus: 64
class_set: "BASIC4"
chr_names: ["Chr6D"]  # list of chromosomes to process: null (all) or a specific list e.g. ["chr1", "chr21"]
logging_level: "INFO"  # verbosity level (set to "ERROR" to reduce logging volume)

bam_type: "LONG"
signal_set: "LONG"
signal_set_origin: "LONG"
stream: False
scan_target_intervals: False
#ps aux | grep call.py
#ps -ef | grep train.py
#ps -ef | grep generate.py
#conda activate cue
#nohup python /mnt/mnt_data/dzj_dirs/mnt/mnt_data/dzj_dirs/cue3/engine/call.py --data_config /mnt/mnt_data/dzj_dirs/mnt/mnt_data/dzj_dirs/css20x/Chr6D/data.yaml --model_config /mnt/mnt_data/dzj_dirs/mnt/mnt_data/dzj_dirs/css20x/Chr6D/model.yaml 2> generate.log &



#head -n 1000000000000000  generate.log

#cd ../
#cd /mnt/mnt_data/dzj_dirs/mnt/mnt_data/dzj_dirs/css20x/Chr6D
